// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2IziTBa3Tmy06xHOsKcPrWb8AIBe7jSU',
    appId: '1:195401418808:web:a2089f3e32b1760017becd',
    messagingSenderId: '195401418808',
    projectId: 'flutterchatapp-357a8',
    authDomain: 'flutterchatapp-357a8.firebaseapp.com',
    storageBucket: 'flutterchatapp-357a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASabpY4yDJ3jFUnzRGpFC7lucWFeNubXw',
    appId: '1:195401418808:android:d1f6e396cf9659cc17becd',
    messagingSenderId: '195401418808',
    projectId: 'flutterchatapp-357a8',
    storageBucket: 'flutterchatapp-357a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFnVKCX0t78tRQZzKQ-iyuTpKzXsVZTfQ',
    appId: '1:195401418808:ios:df69809c1e75656917becd',
    messagingSenderId: '195401418808',
    projectId: 'flutterchatapp-357a8',
    storageBucket: 'flutterchatapp-357a8.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFnVKCX0t78tRQZzKQ-iyuTpKzXsVZTfQ',
    appId: '1:195401418808:ios:a06d1acb88edfd3817becd',
    messagingSenderId: '195401418808',
    projectId: 'flutterchatapp-357a8',
    storageBucket: 'flutterchatapp-357a8.appspot.com',
    iosBundleId: 'com.example.flutterChatApp.RunnerTests',
  );
}
